# Application
app.base-images-url=http://localhost:8181/gabaritos/
app.base-images-path=/Users/computex/workspace/abcde/api/uploads/gabaritos/
app.api-python-url=http://localhost:8000
app.web-url=http://localhost:4200/#/
api.basepath=/api/v1/

# SQL Config
spring.datasource.url=jdbc:postgresql://localhost:5432/lcs_scan
spring.datasource.username=dev
spring.datasource.password=dev

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true